global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [localhost:9090]
    labels:
      app: prometheus
- job_name: node-exporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [localhost:9100]
    labels:
      app: node-exporter
  relabel_configs:
  - target_label: __scrape_interval__
    replacement: 1m
- job_name: grafna
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [localhost:3000]
    labels:
      app: grafana
- job_name: loki
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [localhost:3100]
    labels:
      app: loki
- job_name: vector
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [localhost:9598]
    labels:
      app: vector
